///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SalesModel {


  int? id;
  String? orderId;
  String? buyerName;
  String? buyerEmail;
  String? sellerName;
  String? sellerEmail;
  String? productName;
  String? productQuantity;
  String? totalPrice;
  String? createdAt;
  String? updatedAt;
  String? status;

  SalesModel({
    this.id,
    this.orderId,
    this.buyerName,
    this.buyerEmail,
    this.sellerName,
    this.sellerEmail,
    this.productName,
    this.productQuantity,
    this.totalPrice,
    this.createdAt,
    this.updatedAt,
    this.status,
  });
  SalesModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    orderId = json['order_id']?.toString();
    buyerName = json['buyer_name']?.toString();
    buyerEmail = json['buyer_email']?.toString();
    sellerName = json['seller_name']?.toString();
    sellerEmail = json['seller_email']?.toString();
    productName = json['product_name']?.toString();
    productQuantity = json['product_quantity']?.toString();
    totalPrice = json['total_price']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['order_id'] = orderId;
    data['buyer_name'] = buyerName;
    data['buyer_email'] = buyerEmail;
    data['seller_name'] = sellerName;
    data['seller_email'] = sellerEmail;
    data['product_name'] = productName;
    data['product_quantity'] = productQuantity;
    data['total_price'] = totalPrice;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['status'] = status;
    return data;
  }
}
